<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5236" started-at="2020-02-22T18:32:50Z" finished-at="2020-02-22T18:32:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5236" started-at="2020-02-22T18:32:50Z" finished-at="2020-02-22T18:32:55Z">
      <class name="Task2.APITests">
        <test-method status="PASS" signature="validateBookingIsCreatedSuccessfully(java.lang.String, java.lang.String)[pri:0, instance:Task2.APITests@6cc4c815]" name="validateBookingIsCreatedSuccessfully" duration-ms="3168" started-at="2020-02-22T20:32:50Z" data-provider="BooksData" finished-at="2020-02-22T20:32:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2019-02-25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2019-02-26]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBookingIsCreatedSuccessfully -->
        <test-method status="PASS" signature="validateBookingIsCreatedSuccessfully(java.lang.String, java.lang.String)[pri:0, instance:Task2.APITests@6cc4c815]" name="validateBookingIsCreatedSuccessfully" duration-ms="794" started-at="2020-02-22T20:32:53Z" data-provider="BooksData" finished-at="2020-02-22T20:32:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2020-03-26]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2020-03-27]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBookingIsCreatedSuccessfully -->
        <test-method status="FAIL" signature="validateBookingDetailsIsDisplayedSuccessfully()[pri:0, instance:Task2.APITests@6cc4c815]" name="validateBookingDetailsIsDisplayedSuccessfully" duration-ms="1248" started-at="2020-02-22T20:32:54Z" finished-at="2020-02-22T20:32:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at Task2.APITests.validateBookingDetailsIsDisplayedSuccessfully(APITests.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBookingDetailsIsDisplayedSuccessfully -->
      </class> <!-- Task2.APITests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
